In [2]:
import pandas as pd
import numpy as np

In [4]:
pop = pd.read_csv("population.csv")
pop.head(10)

,Year,District.Code,District.Name,Neighborhood.Code,Neighborhood.Name,Gender,Age,Number
0,2017,1,Ciutat Vella,1,el Raval,Male,0-4,224
1,2017,1,Ciutat Vella,2,el Barri Gòtic,Male,0-4,50
2,2017,1,Ciutat Vella,3,la Barceloneta,Male,0-4,43
3,2017,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Male,0-4,95
4,2017,2,Eixample,5,el Fort Pienc,Male,0-4,124
5,2017,2,Eixample,6,la Sagrada Família,Male,0-4,191
6,2017,2,Eixample,7,la Dreta de l'Eixample,Male,0-4,176
7,2017,2,Eixample,8,l'Antiga Esquerra de l'Eixample,Male,0-4,158
8,2017,2,Eixample,9,la Nova Esquerra de l'Eixample,Male,0-4,220
9,2017,2,Eixample,10,Sant Antoni,Male,0-4,143

In [7]:
pop.dtypes

Year                  int64
District.Code         int64
District.Name        object
Neighborhood.Code     int64
Neighborhood.Name    object
Gender               object
Age                  object
Number                int64
dtype: object

In [8]:
null_cols = pop.isnull().sum()
null_cols[null_cols > 0]

Series([], dtype: int64)

In [9]:
for year in set(pop["Year"]):
   print(pop[pop["Year"] == year].head(10))

       Year  District.Code District.Name  Neighborhood.Code  \
14016  2016              1  Ciutat Vella                  1
14017  2016              1  Ciutat Vella                  2
14018  2016              1  Ciutat Vella                  3
14019  2016              1  Ciutat Vella                  4
14020  2016              2      Eixample                  5
14021  2016              2      Eixample                  6
14022  2016              2      Eixample                  7
14023  2016              2      Eixample                  8
14024  2016              2      Eixample                  9
14025  2016              2      Eixample                 10

                           Neighborhood.Name Gender  Age  Number
14016                               el Raval   Male  0-4     209
14017                         el Barri Gòtic   Male  0-4      45
14018                         la Barceloneta   Male  0-4      56
14019  Sant Pere, Santa Caterina i la Ribera   Male  0-4      84
14020                          el Fort Pienc   Male  0-4     143
14021                     la Sagrada Família   Male  0-4     198
14022                 la Dreta de l'Eixample   Male  0-4     209
14023        l'Antiga Esquerra de l'Eixample   Male  0-4     173
14024         la Nova Esquerra de l'Eixample   Male  0-4     227
14025                            Sant Antoni   Male  0-4     164
   Year  District.Code District.Name  Neighborhood.Code  \
0  2017              1  Ciutat Vella                  1
1  2017              1  Ciutat Vella                  2
2  2017              1  Ciutat Vella                  3
3  2017              1  Ciutat Vella                  4
4  2017              2      Eixample                  5
5  2017              2      Eixample                  6
6  2017              2      Eixample                  7
7  2017              2      Eixample                  8
8  2017              2      Eixample                  9
9  2017              2      Eixample                 10

                       Neighborhood.Name Gender  Age  Number
0                               el Raval   Male  0-4     224
1                         el Barri Gòtic   Male  0-4      50
2                         la Barceloneta   Male  0-4      43
3  Sant Pere, Santa Caterina i la Ribera   Male  0-4      95
4                          el Fort Pienc   Male  0-4     124
5                     la Sagrada Família   Male  0-4     191
6                 la Dreta de l'Eixample   Male  0-4     176
7        l'Antiga Esquerra de l'Eixample   Male  0-4     158
8         la Nova Esquerra de l'Eixample   Male  0-4     220
9                            Sant Antoni   Male  0-4     143
       Year  District.Code District.Name  Neighborhood.Code  \
56064  2013              1  Ciutat Vella                  1
56065  2013              1  Ciutat Vella                  2
56066  2013              1  Ciutat Vella                  3
56067  2013              1  Ciutat Vella                  4
56068  2013              2      Eixample                  5
56069  2013              2      Eixample                  6
56070  2013              2      Eixample                  7
56071  2013              2      Eixample                  8
56072  2013              2      Eixample                  9
56073  2013              2      Eixample                 10

                           Neighborhood.Name Gender  Age  Number
56064                               el Raval   Male  0-4     227
56065                         el Barri Gòtic   Male  0-4      49
56066                         la Barceloneta   Male  0-4      50
56067  Sant Pere, Santa Caterina i la Ribera   Male  0-4      78
56068                          el Fort Pienc   Male  0-4     120
56069                     la Sagrada Família   Male  0-4     221
56070                 la Dreta de l'Eixample   Male  0-4     165
56071        l'Antiga Esquerra de l'Eixample   Male  0-4     125
56072         la Nova Esquerra de l'Eixample   Male  0-4     200
56073                            Sant Antoni   Male  0-4     149
       Year  District.Code District.Name  Neighborhood.Code  \
42048  2014              1  Ciutat Vella                  1
42049  2014              1  Ciutat Vella                  2
42050  2014              1  Ciutat Vella                  3
42051  2014              1  Ciutat Vella                  4
42052  2014              2      Eixample                  5
42053  2014              2      Eixample                  6
42054  2014              2      Eixample                  7
42055  2014              2      Eixample                  8
42056  2014              2      Eixample                  9
42057  2014              2      Eixample                 10

                           Neighborhood.Name Gender  Age  Number
42048                               el Raval   Male  0-4     210
42049                         el Barri Gòtic   Male  0-4      51
42050                         la Barceloneta   Male  0-4      55
42051  Sant Pere, Santa Caterina i la Ribera   Male  0-4      86
42052                          el Fort Pienc   Male  0-4     120
42053                     la Sagrada Família   Male  0-4     162
42054                 la Dreta de l'Eixample   Male  0-4     199
42055        l'Antiga Esquerra de l'Eixample   Male  0-4     174
42056         la Nova Esquerra de l'Eixample   Male  0-4     200
42057                            Sant Antoni   Male  0-4     154
       Year  District.Code District.Name  Neighborhood.Code  \
28032  2015              1  Ciutat Vella                  1
28033  2015              1  Ciutat Vella                  2
28034  2015              1  Ciutat Vella                  3
28035  2015              1  Ciutat Vella                  4
28036  2015              2      Eixample                  5
28037  2015              2      Eixample                  6
28038  2015              2      Eixample                  7
28039  2015              2      Eixample                  8
28040  2015              2      Eixample                  9
28041  2015              2      Eixample                 10

                           Neighborhood.Name Gender  Age  Number
28032                               el Raval   Male  0-4     227
28033                         el Barri Gòtic   Male  0-4      34
28034                         la Barceloneta   Male  0-4      40
28035  Sant Pere, Santa Caterina i la Ribera   Male  0-4      92
28036                          el Fort Pienc   Male  0-4     127
28037                     la Sagrada Família   Male  0-4     217
28038                 la Dreta de l'Eixample   Male  0-4     191
28039        l'Antiga Esquerra de l'Eixample   Male  0-4     160
28040         la Nova Esquerra de l'Eixample   Male  0-4     221
28041                            Sant Antoni   Male  0-4     149

In [12]:
pop.columns

Index(['Year', 'District.Code', 'District.Name', 'Neighborhood.Code',
       'Neighborhood.Name', 'Gender', 'Age', 'Number'],
      dtype='object')

In [17]:
alone = pd.read_csv("dfTOTAL.csv")

In [18]:
alone.head()

   Unnamed: 0  Order        Name  Gender       Decade  Frequency
0           0      1       MARIA  Female  Before 1930       2085
1           1      2      CARMEN  Female  Before 1930       1463
2           2      3      JOSEFA  Female  Before 1930       1032
3           3      4  MONTSERRAT  Female  Before 1930        879
4           4      5        ROSA  Female  Before 1930        762

In [22]:
test = pd.read_csv("./life_expectancy/Life_expectancy_of_the-city_of_Barcelona.csv")

In [20]:
test

,Dte.,Barris,2006-2010,2007-2011,2008-2012,2009-2013,2010-2014
0,BARCELONA,NaN,82.5,82.8,83.1,83.4,83.8
1,1,1. el Raval,82.6,79.7,79.9,80.3,80.7
2,1,2. el Barri Gòtic,84.7,81.3,81.5,81.3,81.4
3,1,3. la Barceloneta,83.3,80.0,80.1,80.4,80.3
4,1,"4. Sant Pere, Santa Caterina i la Ribera",85.1,82.1,82,82.4,82.0
5,2,5. el Fort Pienc,86.7,84.2,84.3,84.3,84.3
6,2,6. la Sagrada Família,86.5,83.9,84.2,84.3,84.6
7,2,7. la Dreta de l'Eixample,84.5,82.2,82.5,82.9,82.9
8,2,8. l'Antiga Esquerra de l'Eixample,86.1,83.5,83.7,83.8,84.2
9,2,9. la Nova Esquerra de l'Eixample,86.4,83.9,84,84.6,85.2
10,2,10. Sant Antoni,85.8,83.2,83.3,83.8,84.0
11,3,11. el Poble Sec - Parc Montjuïc,84.9,82.1,82.4,82.6,82.8
12,3,12. la Marina del Prat Vermell - Zona Franca,NaN,NaN,NaN,NaN,NaN
13,3,13. la Marina de Port,85.9,83.3,83.3,84.0,83.9
14,3,14. la Font de la Guatlla,85.4,82.0,81.8,82.3,81.7
15,3,15. Hostafrancs,84.6,82.3,82.6,82.6,83.7
16,3,16. la Bordeta,86.5,83.8,83.2,83.3,83.8
17,3,17. Sants - Badal,86.3,83.8,84.1,84.5,85.1
18,3,18. Sants,85.8,83.2,83.4,83.7,84.1
19,4,19. les Corts,86.5,84.4,84.6,85.3,85.5
20,4,20. la Maternitat i Sant Ramon,87.3,84.9,85,85.8,86.5
21,4,21. Pedralbes,87.1,85.2,85.5,86.5,86.2
22,5,"22. Vallvidrera, el Tibidabo i les Planes",81.2,79.1,79.2,80.1,80.6
23,5,23. Sarrià,87.8,84.7,84.5,84.6,84.5
24,5,24. les Tres Torres,87.5,85.6,85.6,85.9,86.2
25,5,25. Sant Gervasi - la Bonanova,86.8,84.4,84.5,84.7,84.9
26,5,26. Sant Gervasi - Galvany,86.6,84.2,84.2,84.6,84.7
27,5,27. el Putxet i el Farró,87.3,84.8,85.1,85.3,85.6
28,6,28. Vallcarca i els Penitents,85.7,83.4,83.8,83.6,83.9
29,6,29. el Coll,85.8,83.9,84.5,85.0,85.2
...,...,...,...,...,...,...,...
44,8,44. Vilapicina i la Torre Llobeta,86.0,83.4,83.7,83.5,83.6
45,8,45. Porta,85.2,83.1,83.4,84.0,84.5
46,8,46. el Turó de la Peira,85.7,83.4,84.1,84.8,85.6
47,8,47. Can Peguera,78.6,76.2,76.2,78.1,80.0
48,8,48. la Guineueta,84.8,82.4,82.6,83.2,84.2
49,8,49. Canyelles,86.0,82.8,83,83.0,83.1
50,8,50. les Roquetes,83.8,81.2,81.2,81.4,81.9
51,8,51. Verdun,84.5,82.3,82.5,82.5,83.2
52,8,52. la Prosperitat,85.7,83.2,83.8,84.0,84.5
53,8,53. la Trinitat Nova,82.9,80.3,79.8,79.8,80.1
54,8,54. Torre Baró,NaN,75.4,74.7,75.2,77.2
55,8,55. Ciutat Meridiana,84.2,81.6,82,83.0,83.7
56,8,56. Vallbona,NaN,NaN,NaN,NaN,NaN
57,9,57. la Trinitat Vella,83.8,81.7,82.7,83.8,85.1
58,9,58. Baró de Viver,78.5,75.6,…,78.2,80.3
59,9,59. el Bon Pastor,83.5,81.3,81.7,82.1,82.2
60,9,60. Sant Andreu,85.5,83.2,83.7,83.9,84.7
61,9,61. la Sagrera,87.1,84.4,84.7,84.8,85.4
62,9,62. el Congrés i els Indians,86.1,83.6,83.9,84.7,84.8
63,9,63. Navas,86.5,84.1,84.4,85.4,86.3
64,10,64. el Camp de l'Arpa del Clot,86.3,83.8,84.4,84.6,85.0
65,10,65. el Clot,85.6,83.7,84.1,84.5,85.1
66,10,66. el Parc i la Llacuna del Poblenou,85.5,82.8,83.1,83.4,83.2
67,10,67. la Vila Olímpica del Poblenou,88.8,85.0,85.2,85.6,85.4
68,10,68. el Poblenou,85.1,82.4,82.4,83.0,83.5
69,10,69. Diagonal Mar i el Front Marítim del Poblenou,85.3,84.2,84.4,85.0,85.3
70,10,70. el Besòs i el Maresme,83.6,81.7,82,82.4,83.1
71,10,71. Provençals del Poblenou,84.6,82.8,83.1,83.6,85.1
72,10,72. Sant Martí de Provençals,85.6,83.0,83.2,83.4,83.9
73,10,73. la Verneda i la Pau,85.1,82.9,82.9,83.3,83.9

In [32]:
single = pd.read_csv("./population_by_neighborhood_and_genre/Population_living_alone/2018_padro_viu_sola_edat_quinquennal.csv")
single.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Sexe,Edat quinquennal,Nombre
0,2018,1,Ciutat Vella,1,el Raval,Home,< 25 anys,98
1,2018,1,Ciutat Vella,2,el Barri Gòtic,Home,< 25 anys,53
2,2018,1,Ciutat Vella,3,la Barceloneta,Home,< 25 anys,37
3,2018,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Home,< 25 anys,73
4,2018,2,Eixample,5,el Fort Pienc,Home,< 25 anys,25

In [33]:
single.columns

Index(['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Sexe', 'Edat quinquennal', 'Nombre'],
      dtype='object')

In [41]:
single.dtypes
single.columns = ['Any', 'Codi_Districte', 'Nom_Districte', 'Codi_Barri', 'Nom_Barri',
       'Sexe', 'Age_by_5', 'Number']
single.head()

,Any,Codi_Districte,Nom_Districte,Codi_Barri,Nom_Barri,Sexe,Age_by_5,Number
0,2018,1,Ciutat Vella,1,el Raval,Home,< 25 anys,98
1,2018,1,Ciutat Vella,2,el Barri Gòtic,Home,< 25 anys,53
2,2018,1,Ciutat Vella,3,la Barceloneta,Home,< 25 anys,37
3,2018,1,Ciutat Vella,4,"Sant Pere, Santa Caterina i la Ribera",Home,< 25 anys,73
4,2018,2,Eixample,5,el Fort Pienc,Home,< 25 anys,25

In [43]:
single_by_district = single[["Any", "Codi_Districte", "Nom_Districte", "Sexe", "Age_by_5", "Number"]]
single_by_district.head()

    Any  Codi_Districte Nom_Districte  Sexe   Age_by_5  Number
0  2018               1  Ciutat Vella  Home  < 25 anys      98
1  2018               1  Ciutat Vella  Home  < 25 anys      53
2  2018               1  Ciutat Vella  Home  < 25 anys      37
3  2018               1  Ciutat Vella  Home  < 25 anys      73
4  2018               2      Eixample  Home  < 25 anys      25

In [48]:
single_by_district[single_by_district['Any']==2018].groupby(['Nom_Districte','Age_by_5']).sum()

                                      Any  Codi_Districte  Number
Nom_Districte       Age_by_5
Ciutat Vella        100 anys i més  16144               8      11
                    25-29 anys      16144               8    1616
                    30-34 anys      16144               8    1866
                    35-39 anys      16144               8    1822
                    40-44 anys      16144               8    1488
                    45-49 anys      16144               8    1209
                    50-54 anys      16144               8    1022
                    55-59 anys      16144               8     914
                    60-64 anys      16144               8     941
                    65-69 anys      16144               8     863
                    70-74 anys      16144               8     864
                    75-79 anys      16144               8     668
                    80-84 anys      16144               8     841
                    85-89 anys      16144               8     709
                    90-94 anys      16144               8     407
                    95-99 anys      16144               8      91
                    < 25 anys       16144               8     562
Eixample            100 anys i més  24216              24      64
                    25-29 anys      24216              24    2252
                    30-34 anys      24216              24    3101
                    35-39 anys      24216              24    3080
                    40-44 anys      24216              24    2708
                    45-49 anys      24216              24    2372
                    50-54 anys      24216              24    2454
                    55-59 anys      24216              24    2458
                    60-64 anys      24216              24    2637
                    65-69 anys      24216              24    2884
                    70-74 anys      24216              24    3012
                    75-79 anys      24216              24    2545
                    80-84 anys      24216              24    2971
...                                   ...             ...     ...
Sants-Montjuïc      40-44 anys      32288              48    1872
                    45-49 anys      32288              48    1594
                    50-54 anys      32288              48    1604
                    55-59 anys      32288              48    1560
                    60-64 anys      32288              48    1592
                    65-69 anys      32288              48    1645
                    70-74 anys      32288              48    1802
                    75-79 anys      32288              48    1527
                    80-84 anys      32288              48    1945
                    85-89 anys      32288              48    1694
                    90-94 anys      32288              48     813
                    95-99 anys      32288              48     160
                    < 25 anys       32288              48     355
Sarrià-Sant Gervasi 100 anys i més  24216              60      38
                    25-29 anys      24216              60     845
                    30-34 anys      24216              60    1137
                    35-39 anys      24216              60    1087
                    40-44 anys      24216              60    1122
                    45-49 anys      24216              60    1052
                    50-54 anys      24216              60    1126
                    55-59 anys      24216              60    1086
                    60-64 anys      24216              60    1215
                    65-69 anys      24216              60    1413
                    70-74 anys      24216              60    1525
                    75-79 anys      24216              60    1293
                    80-84 anys      24216              60    1391
                    85-89 anys      24216              60    1348
                    90-94 anys      24216              60     783
                    95-99 anys      24216              60     229
                    < 25 anys       24216              60     336

[170 rows x 3 columns]